version: latest

services: 

  cursos_service:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    container_name: servicio_B

  #docker-compose up --build

  # postgres:
  #   image: postgres
  #   restart: always
  #   environment: 
  #     - DATABASE_HOST=34.73.118.80
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=dinosaurio123
  #     - POSTGRES_DB=postgres
  #   ports: 
  #     - 5432:5432

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment: 
  #     PGADMIN_DEFAULT_EMAIL: "cdmorau@unal.edu.co"
  #     PGADMIN_DEFAULT_PASSWORD: "cdmorau"
  #   ports:
  #     - "80:80"
  #   depends_on: 
  #     - postgres 
  